### ISSUE TITLE
FSharp.OpenApi

### ISSUE THREAD

**Issue by jkone27** [akhansari/AspFeat#10]
what about the beautiful https://github.com/akhansari/FSharp.OpenApi 
i see that has been archived, but i really needed only the OpenApi builder CE which looked awesome.

Could that be re-surrected? :) :) :) 

or would it be possible to just generate a separate package for that only ?

i really liked the possibility to interop/integrat with existing F# frameworks (Giraffe/Saturn/Falco)

This project is awesome ! thanks !!! 👍 🔝 🙏 🤩 😊

**Comment by akhansari** [comment]
TBH, I didn't know that the lib was used so I archived it to focus on AspFeat.

I should update it and bring it back to life 👍

**Comment by jkone27** [comment]
not at the moment, but i was very interested for the openapi generation part and swagger, as i found no other ways to generate the openapi document, your library seemed to me the most promising. I am trying it out for an F# template atm, but first i need to have a dynamic openapi/swagger working in any way 🎩  😸

**Comment by jkone27** [comment]
if you could re-publish the package it would be amazing :)

**Comment by akhansari** [comment]
Hello @jkone27, I released a new version for FSharp.OpenApi
Tell me if you encounter any problems with.
